-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCU4yGgGnyrJ/q258
tXS6+cWEcfaQmgD61HdOuY/uNAGgCgYIKoZIzj0DAQehRANCAARbWZAnTpRfi6fK
SWWl8N2+TCfsqSOyZPrtBWKW/3Xu7/p1i2lgsz4eFsmOCupKfdOPJHCib5Rl40Uw
TR3Qx7mG
-----END PRIVATE KEY-----